name: Transform Tokens

on:
  push:
    branches:
      - design
    paths:
      - figma_token.json

jobs:
  transform-tokens:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: design
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run Token Transformer
        continue-on-error: true
        run: |
          npm install -g style-dictionary
          style-dictionary build --config ./sd.config.js

      - name: Create pull request
        uses: thomaseizinger/create-pull-request@master
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          head: design
          base: main
          title: "design-tokens: Update design tokens"
          body: |
            This PR updates design tokens from Figma.
            Changes include:
            - Updated color tokens
            - Updated spacing tokens
            - Updated typography tokens
